# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.8

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/tyamgin/clion-2017.2.1/bin/cmake/bin/cmake

# The command to remove a file.
RM = /home/tyamgin/clion-2017.2.1/bin/cmake/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/tyamgin/CLionProjects/highload

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/tyamgin/CLionProjects/highload

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/tyamgin/clion-2017.2.1/bin/cmake/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/tyamgin/clion-2017.2.1/bin/cmake/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/tyamgin/CLionProjects/highload/CMakeFiles /home/tyamgin/CLionProjects/highload/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/tyamgin/CLionProjects/highload/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named highload

# Build rule for target.
highload: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 highload
.PHONY : highload

# fast build rule for target.
highload/fast:
	$(MAKE) -f CMakeFiles/highload.dir/build.make CMakeFiles/highload.dir/build
.PHONY : highload/fast

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/highload.dir/build.make CMakeFiles/highload.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/highload.dir/build.make CMakeFiles/highload.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/highload.dir/build.make CMakeFiles/highload.dir/main.cpp.s
.PHONY : main.cpp.s

model/entity.o: model/entity.cpp.o

.PHONY : model/entity.o

# target to build an object file
model/entity.cpp.o:
	$(MAKE) -f CMakeFiles/highload.dir/build.make CMakeFiles/highload.dir/model/entity.cpp.o
.PHONY : model/entity.cpp.o

model/entity.i: model/entity.cpp.i

.PHONY : model/entity.i

# target to preprocess a source file
model/entity.cpp.i:
	$(MAKE) -f CMakeFiles/highload.dir/build.make CMakeFiles/highload.dir/model/entity.cpp.i
.PHONY : model/entity.cpp.i

model/entity.s: model/entity.cpp.s

.PHONY : model/entity.s

# target to generate assembly for a file
model/entity.cpp.s:
	$(MAKE) -f CMakeFiles/highload.dir/build.make CMakeFiles/highload.dir/model/entity.cpp.s
.PHONY : model/entity.cpp.s

model/location.o: model/location.cpp.o

.PHONY : model/location.o

# target to build an object file
model/location.cpp.o:
	$(MAKE) -f CMakeFiles/highload.dir/build.make CMakeFiles/highload.dir/model/location.cpp.o
.PHONY : model/location.cpp.o

model/location.i: model/location.cpp.i

.PHONY : model/location.i

# target to preprocess a source file
model/location.cpp.i:
	$(MAKE) -f CMakeFiles/highload.dir/build.make CMakeFiles/highload.dir/model/location.cpp.i
.PHONY : model/location.cpp.i

model/location.s: model/location.cpp.s

.PHONY : model/location.s

# target to generate assembly for a file
model/location.cpp.s:
	$(MAKE) -f CMakeFiles/highload.dir/build.make CMakeFiles/highload.dir/model/location.cpp.s
.PHONY : model/location.cpp.s

model/user.o: model/user.cpp.o

.PHONY : model/user.o

# target to build an object file
model/user.cpp.o:
	$(MAKE) -f CMakeFiles/highload.dir/build.make CMakeFiles/highload.dir/model/user.cpp.o
.PHONY : model/user.cpp.o

model/user.i: model/user.cpp.i

.PHONY : model/user.i

# target to preprocess a source file
model/user.cpp.i:
	$(MAKE) -f CMakeFiles/highload.dir/build.make CMakeFiles/highload.dir/model/user.cpp.i
.PHONY : model/user.cpp.i

model/user.s: model/user.cpp.s

.PHONY : model/user.s

# target to generate assembly for a file
model/user.cpp.s:
	$(MAKE) -f CMakeFiles/highload.dir/build.make CMakeFiles/highload.dir/model/user.cpp.s
.PHONY : model/user.cpp.s

model/visit.o: model/visit.cpp.o

.PHONY : model/visit.o

# target to build an object file
model/visit.cpp.o:
	$(MAKE) -f CMakeFiles/highload.dir/build.make CMakeFiles/highload.dir/model/visit.cpp.o
.PHONY : model/visit.cpp.o

model/visit.i: model/visit.cpp.i

.PHONY : model/visit.i

# target to preprocess a source file
model/visit.cpp.i:
	$(MAKE) -f CMakeFiles/highload.dir/build.make CMakeFiles/highload.dir/model/visit.cpp.i
.PHONY : model/visit.cpp.i

model/visit.s: model/visit.cpp.s

.PHONY : model/visit.s

# target to generate assembly for a file
model/visit.cpp.s:
	$(MAKE) -f CMakeFiles/highload.dir/build.make CMakeFiles/highload.dir/model/visit.cpp.s
.PHONY : model/visit.cpp.s

state.o: state.cpp.o

.PHONY : state.o

# target to build an object file
state.cpp.o:
	$(MAKE) -f CMakeFiles/highload.dir/build.make CMakeFiles/highload.dir/state.cpp.o
.PHONY : state.cpp.o

state.i: state.cpp.i

.PHONY : state.i

# target to preprocess a source file
state.cpp.i:
	$(MAKE) -f CMakeFiles/highload.dir/build.make CMakeFiles/highload.dir/state.cpp.i
.PHONY : state.cpp.i

state.s: state.cpp.s

.PHONY : state.s

# target to generate assembly for a file
state.cpp.s:
	$(MAKE) -f CMakeFiles/highload.dir/build.make CMakeFiles/highload.dir/state.cpp.s
.PHONY : state.cpp.s

utility.o: utility.cpp.o

.PHONY : utility.o

# target to build an object file
utility.cpp.o:
	$(MAKE) -f CMakeFiles/highload.dir/build.make CMakeFiles/highload.dir/utility.cpp.o
.PHONY : utility.cpp.o

utility.i: utility.cpp.i

.PHONY : utility.i

# target to preprocess a source file
utility.cpp.i:
	$(MAKE) -f CMakeFiles/highload.dir/build.make CMakeFiles/highload.dir/utility.cpp.i
.PHONY : utility.cpp.i

utility.s: utility.cpp.s

.PHONY : utility.s

# target to generate assembly for a file
utility.cpp.s:
	$(MAKE) -f CMakeFiles/highload.dir/build.make CMakeFiles/highload.dir/utility.cpp.s
.PHONY : utility.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... highload"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... model/entity.o"
	@echo "... model/entity.i"
	@echo "... model/entity.s"
	@echo "... model/location.o"
	@echo "... model/location.i"
	@echo "... model/location.s"
	@echo "... model/user.o"
	@echo "... model/user.i"
	@echo "... model/user.s"
	@echo "... model/visit.o"
	@echo "... model/visit.i"
	@echo "... model/visit.s"
	@echo "... state.o"
	@echo "... state.i"
	@echo "... state.s"
	@echo "... utility.o"
	@echo "... utility.i"
	@echo "... utility.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

